services:
  server:
    build: .
    container_name: iot-server
    volumes:
      - .:/work
    ports:
      - "2222:22"
    networks:
      iotnet:
        ipv4_address: 192.168.2.10

  client:
    build: .
    container_name: iot-client
    volumes:
      - .:/work
    ports:
      - "2223:22"
    depends_on:
      - server
    networks:
      iotnet:
        ipv4_address: 192.168.2.11

networks:
  iotnet:
    external: true
    name: iotnet
