version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: dev
        UID: 1000
        GID: 1000
    container_name: iot-server
    working_dir: /work
    volumes:
      - .:/work
    command: ["bash"]
    networks:
      iotnet:
        ipv4_address: 192.168.2.10

  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: dev
        UID: 1000
        GID: 1000
    container_name: iot-client
    working_dir: /work
    volumes:
      - .:/work
    command: ["bash"]
    depends_on:
      - server
    networks:
      iotnet:
        ipv4_address: 192.168.2.11

networks:
  iotnet:
    external: true
    name: iotnet
