services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    hostname: mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto/config
    networks:
      iotnet:
        ipv4_address: 192.168.2.100
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: DockerFile_python
    container_name: python-server
    hostname: pyserv
    volumes:
      - .:/work
    ports:
      - "2222:22"
    networks:
      iotnet:
        ipv4_address: 192.168.2.10

  client:
    build:
      context: .
      dockerfile: DockerFile_python
    container_name: python-client
    hostname: pycli
    volumes:
      - .:/work
    ports:
      - "2223:22"
    depends_on:
      - server
      - mqtt-broker
    networks:
      iotnet:
        ipv4_address: 192.168.2.11

  client2:
    build:
      context: .
      dockerfile: DockerFile_python
    container_name: python-client2
    hostname: pycli2
    volumes:
      - .:/work
    ports:
      - "2224:22"
    depends_on:
      - server
      - mqtt-broker
    networks:
      iotnet:
        ipv4_address: 192.168.2.12

networks:
  iotnet:
    name: iotnet
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1
